/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountProfileSummary } from './accountProfileSummary';
import { PublicPlatformOutput } from './publicPlatformOutput';

export class Account {
    'id': string;
    'platform': PublicPlatformOutput;
    'providerAccountId': string;
    'profileId': AccountProfileSummary;
    'username': string;
    'displayName': string;
    'profileUrl'?: string;
    'avatarUrl'?: string;
    'status': Account.StatusEnum;
    'isActive': boolean;
    'connectedAt': Date;
    'lastSyncedAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "PublicPlatformOutput"
        },
        {
            "name": "providerAccountId",
            "baseName": "providerAccountId",
            "type": "string"
        },
        {
            "name": "profileId",
            "baseName": "profileId",
            "type": "AccountProfileSummary"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "profileUrl",
            "baseName": "profileUrl",
            "type": "string"
        },
        {
            "name": "avatarUrl",
            "baseName": "avatarUrl",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Account.StatusEnum"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean"
        },
        {
            "name": "connectedAt",
            "baseName": "connectedAt",
            "type": "Date"
        },
        {
            "name": "lastSyncedAt",
            "baseName": "lastSyncedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Account.attributeTypeMap;
    }
}

export namespace Account {
    export enum StatusEnum {
        Connected = <any> 'connected',
        NeedsReauth = <any> 'needsReauth',
        Disconnected = <any> 'disconnected',
        Disabled = <any> 'disabled'
    }
}
