/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Account } from './account';
import { Pagination } from './pagination';

export class AccountsListResponse {
    'accounts': Array<Account>;
    'pagination'?: Pagination;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<Account>"
        },
        {
            "name": "pagination",
            "baseName": "pagination",
            "type": "Pagination"
        }    ];

    static getAttributeTypeMap() {
        return AccountsListResponse.attributeTypeMap;
    }
}

