/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiPostAccount } from './apiPostAccount';
import { PublicPlatformInput } from './publicPlatformInput';

export class ApiPostPlatformResult {
    'platform': PublicPlatformInput;
    'accountId': ApiPostAccount;
    'status': ApiPostPlatformResult.StatusEnum;
    'platformPostUrl'?: string;
    'error'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "platform",
            "baseName": "platform",
            "type": "PublicPlatformInput"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "ApiPostAccount"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ApiPostPlatformResult.StatusEnum"
        },
        {
            "name": "platformPostUrl",
            "baseName": "platformPostUrl",
            "type": "string"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApiPostPlatformResult.attributeTypeMap;
    }
}

export namespace ApiPostPlatformResult {
    export enum StatusEnum {
        Draft = <any> 'draft',
        Scheduled = <any> 'scheduled',
        Pending = <any> 'pending',
        Publishing = <any> 'publishing',
        Published = <any> 'published',
        Failed = <any> 'failed',
        Canceled = <any> 'canceled'
    }
}
