/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiPostPlatformResult } from './apiPostPlatformResult';

export class ApiPost {
    'id': string;
    'title': string | null;
    'content': string;
    'status': string;
    'scheduledFor': Date | null;
    'timezone': string;
    'platforms': Array<ApiPostPlatformResult>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "scheduledFor",
            "baseName": "scheduledFor",
            "type": "Date"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string"
        },
        {
            "name": "platforms",
            "baseName": "platforms",
            "type": "Array<ApiPostPlatformResult>"
        }    ];

    static getAttributeTypeMap() {
        return ApiPost.attributeTypeMap;
    }
}

