/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ConnectCompleteErrorResponse {
    /**
    * Human-readable message, or a camelCase error code (for example `oauthCallbackFailed`) when the platform callback fails.
    */
    'error': string;
    /**
    * Additional detail reported by the platform, when available.
    */
    'errorDescription'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "errorDescription",
            "baseName": "errorDescription",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ConnectCompleteErrorResponse.attributeTypeMap;
    }
}

