/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ConnectCompleteRequest {
    /**
    * OAuth authorization code returned by the platform.
    */
    'code': string;
    /**
    * State returned by `GET /v1/connect/{platform}`.
    */
    'state': string;
    /**
    * PostZen profile id used when the connection was initiated.
    */
    'profileId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "profileId",
            "baseName": "profileId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ConnectCompleteRequest.attributeTypeMap;
    }
}

