/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Account } from './account';
import { PublicPlatformOutput } from './publicPlatformOutput';

export class ConnectCompleteResponse {
    'message': string;
    'platform': PublicPlatformOutput;
    'profileId': string;
    'status': ConnectCompleteResponse.StatusEnum;
    'missingScopes'?: Array<string>;
    'connectedAccountCount'?: number;
    'accounts'?: Array<Account>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "PublicPlatformOutput"
        },
        {
            "name": "profileId",
            "baseName": "profileId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ConnectCompleteResponse.StatusEnum"
        },
        {
            "name": "missingScopes",
            "baseName": "missingScopes",
            "type": "Array<string>"
        },
        {
            "name": "connectedAccountCount",
            "baseName": "connectedAccountCount",
            "type": "number"
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<Account>"
        }    ];

    static getAttributeTypeMap() {
        return ConnectCompleteResponse.attributeTypeMap;
    }
}

export namespace ConnectCompleteResponse {
    export enum StatusEnum {
        Connected = <any> 'connected',
        NeedsReauth = <any> 'needsReauth'
    }
}
