/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiPost } from './apiPost';

export class CreatePostResponse {
    'post': ApiPost;
    'message': CreatePostResponse.MessageEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "post",
            "baseName": "post",
            "type": "ApiPost"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "CreatePostResponse.MessageEnum"
        }    ];

    static getAttributeTypeMap() {
        return CreatePostResponse.attributeTypeMap;
    }
}

export namespace CreatePostResponse {
    export enum MessageEnum {
        PostPublishedSuccessfully = <any> 'Post published successfully',
        PostScheduledSuccessfully = <any> 'Post scheduled successfully',
        DraftCreatedSuccessfully = <any> 'Draft created successfully'
    }
}
