/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreatePostTarget } from './createPostTarget';
import { PostMediaItem } from './postMediaItem';

/**
* Provide exactly one creation mode: `publishNow`, `scheduledFor`, or `isDraft`. `platforms` is required unless `isDraft` is true.
*/
export class CreatePostRequest {
    /**
    * Internal post title. YouTube uses this as the fallback video title when `settings.title` is omitted.
    */
    'title'?: string;
    /**
    * Shared post text. Platform-specific validation still applies.
    */
    'content'?: string = '';
    /**
    * Duplicate URLs are removed before the post is created.
    */
    'mediaItems'?: Array<PostMediaItem>;
    'platforms'?: Array<CreatePostTarget>;
    /**
    * ISO 8601 date for scheduled posts. Must be at least 60 seconds in the future.
    */
    'scheduledFor'?: Date;
    /**
    * Publish synchronously where possible.
    */
    'publishNow'?: boolean;
    /**
    * Create a draft. `platforms` is optional for drafts.
    */
    'isDraft'?: boolean;
    'timezone'?: string = 'UTC';
    'tags'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "mediaItems",
            "baseName": "mediaItems",
            "type": "Array<PostMediaItem>"
        },
        {
            "name": "platforms",
            "baseName": "platforms",
            "type": "Array<CreatePostTarget>"
        },
        {
            "name": "scheduledFor",
            "baseName": "scheduledFor",
            "type": "Date"
        },
        {
            "name": "publishNow",
            "baseName": "publishNow",
            "type": "boolean"
        },
        {
            "name": "isDraft",
            "baseName": "isDraft",
            "type": "boolean"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return CreatePostRequest.attributeTypeMap;
    }
}

