/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PostPlatformSettings } from './postPlatformSettings';
import { PublicPlatformInput } from './publicPlatformInput';

export class CreatePostTarget {
    'platform': PublicPlatformInput;
    /**
    * PostZen account id or provider account id.
    */
    'accountId': string;
    /**
    * Overrides shared `content` for this platform.
    */
    'customContent'?: string;
    'settings'?: PostPlatformSettings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "platform",
            "baseName": "platform",
            "type": "PublicPlatformInput"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "customContent",
            "baseName": "customContent",
            "type": "string"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "PostPlatformSettings"
        }    ];

    static getAttributeTypeMap() {
        return CreatePostTarget.attributeTypeMap;
    }
}

export namespace CreatePostTarget {
}
