/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiPost } from './apiPost';

export class CreatePostReplayResponse {
    'existingPost': ApiPost;
    'message': CreatePostReplayResponse.MessageEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "existingPost",
            "baseName": "existingPost",
            "type": "ApiPost"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "CreatePostReplayResponse.MessageEnum"
        }    ];

    static getAttributeTypeMap() {
        return CreatePostReplayResponse.attributeTypeMap;
    }
}

export namespace CreatePostReplayResponse {
    export enum MessageEnum {
        PostAlreadyExistsForThisRequestId = <any> 'Post already exists for this request id'
    }
}
