/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InstagramSettingsUserTagsInner } from './instagramSettingsUserTagsInner';

export class InstagramSettings {
    'postType'?: InstagramSettings.PostTypeEnum = InstagramSettings.PostTypeEnum.Feed;
    'collaborators'?: Array<string>;
    'userTags'?: Array<InstagramSettingsUserTagsInner>;
    'firstComment'?: string;
    'shareToFeed'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "postType",
            "baseName": "postType",
            "type": "InstagramSettings.PostTypeEnum"
        },
        {
            "name": "collaborators",
            "baseName": "collaborators",
            "type": "Array<string>"
        },
        {
            "name": "userTags",
            "baseName": "userTags",
            "type": "Array<InstagramSettingsUserTagsInner>"
        },
        {
            "name": "firstComment",
            "baseName": "firstComment",
            "type": "string"
        },
        {
            "name": "shareToFeed",
            "baseName": "shareToFeed",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return InstagramSettings.attributeTypeMap;
    }
}

export namespace InstagramSettings {
    export enum PostTypeEnum {
        Feed = <any> 'feed',
        Story = <any> 'story',
        Reel = <any> 'reel',
        Carousel = <any> 'carousel'
    }
}
