/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MediaPresignRequest {
    /**
    * Original file name. PostZen sanitizes it for storage.
    */
    'filename': string;
    'contentType': MediaPresignRequest.ContentTypeEnum;
    /**
    * File size in bytes.
    */
    'size'?: number;
    /**
    * Optional profile scope. If provided, the API key must have access to the profile.
    */
    'profileId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "MediaPresignRequest.ContentTypeEnum"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "profileId",
            "baseName": "profileId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MediaPresignRequest.attributeTypeMap;
    }
}

export namespace MediaPresignRequest {
    export enum ContentTypeEnum {
        ImageJpeg = <any> 'image/jpeg',
        ImageJpg = <any> 'image/jpg',
        ImagePng = <any> 'image/png',
        ImageWebp = <any> 'image/webp',
        ImageGif = <any> 'image/gif',
        VideoMp4 = <any> 'video/mp4',
        VideoMpeg = <any> 'video/mpeg',
        VideoQuicktime = <any> 'video/quicktime',
        VideoAvi = <any> 'video/avi',
        VideoXMsvideo = <any> 'video/x-msvideo',
        VideoWebm = <any> 'video/webm',
        VideoXM4v = <any> 'video/x-m4v',
        ApplicationPdf = <any> 'application/pdf'
    }
}
