/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MediaPresignResponse {
    /**
    * Use this URL for the direct file upload.
    */
    'uploadUrl': string;
    /**
    * Use this URL in post `mediaItems`.
    */
    'publicUrl': string;
    'key': string;
    'type': MediaPresignResponse.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uploadUrl",
            "baseName": "uploadUrl",
            "type": "string"
        },
        {
            "name": "publicUrl",
            "baseName": "publicUrl",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "MediaPresignResponse.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return MediaPresignResponse.attributeTypeMap;
    }
}

export namespace MediaPresignResponse {
    export enum TypeEnum {
        Image = <any> 'image',
        Video = <any> 'video',
        Gif = <any> 'gif',
        Document = <any> 'document'
    }
}
