/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PaymentRequiredErrorDetails {
    'freeTierAccountLimit'?: number;
    'currentAccountCount'?: number;
    'hasPaymentMethod'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "freeTierAccountLimit",
            "baseName": "freeTierAccountLimit",
            "type": "number"
        },
        {
            "name": "currentAccountCount",
            "baseName": "currentAccountCount",
            "type": "number"
        },
        {
            "name": "hasPaymentMethod",
            "baseName": "hasPaymentMethod",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return PaymentRequiredErrorDetails.attributeTypeMap;
    }
}

