/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentRequiredErrorDetails } from './paymentRequiredErrorDetails';

export class PaymentRequiredError {
    'error': string;
    'code': PaymentRequiredError.CodeEnum;
    'reason': PaymentRequiredError.ReasonEnum;
    'documentationUrl': string;
    'dashboardUrl': string;
    'details'?: PaymentRequiredErrorDetails;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "PaymentRequiredError.CodeEnum"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "PaymentRequiredError.ReasonEnum"
        },
        {
            "name": "documentationUrl",
            "baseName": "documentationUrl",
            "type": "string"
        },
        {
            "name": "dashboardUrl",
            "baseName": "dashboardUrl",
            "type": "string"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "PaymentRequiredErrorDetails"
        }    ];

    static getAttributeTypeMap() {
        return PaymentRequiredError.attributeTypeMap;
    }
}

export namespace PaymentRequiredError {
    export enum CodeEnum {
        PaymentRequired = <any> 'paymentRequired'
    }
    export enum ReasonEnum {
        FreeTierExceeded = <any> 'freeTierExceeded',
        XRequiresPaymentMethod = <any> 'xRequiresPaymentMethod'
    }
}
