/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PinterestSettings {
    /**
    * Pinterest board to publish the pin to.
    */
    'boardId'?: string;
    /**
    * Pin title.
    */
    'title'?: string;
    /**
    * Destination link for the pin.
    */
    'link'?: string;
    'altText'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "boardId",
            "baseName": "boardId",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "altText",
            "baseName": "altText",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PinterestSettings.attributeTypeMap;
    }
}

