/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FacebookSettings } from './facebookSettings';
import { InstagramSettings } from './instagramSettings';
import { InstagramSettingsUserTagsInner } from './instagramSettingsUserTagsInner';
import { LinkedInSettings } from './linkedInSettings';
import { PinterestSettings } from './pinterestSettings';
import { ThreadsSettings } from './threadsSettings';
import { TikTokSettings } from './tikTokSettings';
import { XSettings } from './xSettings';
import { YouTubeSettings } from './youTubeSettings';
import { YouTubeSettingsTags } from './youTubeSettingsTags';

/**
* Platform-specific publishing options. Unknown keys are ignored.
*/
export class PostPlatformSettings {
    'postType'?: PostPlatformSettings.PostTypeEnum = PostPlatformSettings.PostTypeEnum.Feed;
    'collaborators'?: Array<string>;
    'userTags'?: Array<InstagramSettingsUserTagsInner>;
    'firstComment'?: string;
    'shareToFeed'?: boolean;
    /**
    * Destination link for the pin.
    */
    'link'?: string;
    'replyControl'?: PostPlatformSettings.ReplyControlEnum;
    'privacyLevel'?: PostPlatformSettings.PrivacyLevelEnum;
    'allowComments'?: boolean;
    'allowDuet'?: boolean;
    'allowStitch'?: boolean;
    'disableComment'?: boolean;
    'disableDuet'?: boolean;
    'disableStitch'?: boolean;
    'videoCoverTimestampMs'?: number;
    'uploadAsDraft'?: boolean;
    'brandContentToggle'?: boolean;
    'brandOrganicToggle'?: boolean;
    'visibility'?: PostPlatformSettings.VisibilityEnum;
    'replySettings'?: PostPlatformSettings.ReplySettingsEnum;
    /**
    * Pin title.
    */
    'title'?: string;
    'privacyStatus'?: PostPlatformSettings.PrivacyStatusEnum;
    'tags'?: YouTubeSettingsTags;
    'categoryId'?: string;
    'madeForKids'?: boolean;
    'notifySubscribers'?: boolean;
    /**
    * Pinterest board to publish the pin to.
    */
    'boardId'?: string;
    'altText'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "postType",
            "baseName": "postType",
            "type": "PostPlatformSettings.PostTypeEnum"
        },
        {
            "name": "collaborators",
            "baseName": "collaborators",
            "type": "Array<string>"
        },
        {
            "name": "userTags",
            "baseName": "userTags",
            "type": "Array<InstagramSettingsUserTagsInner>"
        },
        {
            "name": "firstComment",
            "baseName": "firstComment",
            "type": "string"
        },
        {
            "name": "shareToFeed",
            "baseName": "shareToFeed",
            "type": "boolean"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "replyControl",
            "baseName": "replyControl",
            "type": "PostPlatformSettings.ReplyControlEnum"
        },
        {
            "name": "privacyLevel",
            "baseName": "privacyLevel",
            "type": "PostPlatformSettings.PrivacyLevelEnum"
        },
        {
            "name": "allowComments",
            "baseName": "allowComments",
            "type": "boolean"
        },
        {
            "name": "allowDuet",
            "baseName": "allowDuet",
            "type": "boolean"
        },
        {
            "name": "allowStitch",
            "baseName": "allowStitch",
            "type": "boolean"
        },
        {
            "name": "disableComment",
            "baseName": "disableComment",
            "type": "boolean"
        },
        {
            "name": "disableDuet",
            "baseName": "disableDuet",
            "type": "boolean"
        },
        {
            "name": "disableStitch",
            "baseName": "disableStitch",
            "type": "boolean"
        },
        {
            "name": "videoCoverTimestampMs",
            "baseName": "videoCoverTimestampMs",
            "type": "number"
        },
        {
            "name": "uploadAsDraft",
            "baseName": "uploadAsDraft",
            "type": "boolean"
        },
        {
            "name": "brandContentToggle",
            "baseName": "brandContentToggle",
            "type": "boolean"
        },
        {
            "name": "brandOrganicToggle",
            "baseName": "brandOrganicToggle",
            "type": "boolean"
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "PostPlatformSettings.VisibilityEnum"
        },
        {
            "name": "replySettings",
            "baseName": "replySettings",
            "type": "PostPlatformSettings.ReplySettingsEnum"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "privacyStatus",
            "baseName": "privacyStatus",
            "type": "PostPlatformSettings.PrivacyStatusEnum"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "YouTubeSettingsTags"
        },
        {
            "name": "categoryId",
            "baseName": "categoryId",
            "type": "string"
        },
        {
            "name": "madeForKids",
            "baseName": "madeForKids",
            "type": "boolean"
        },
        {
            "name": "notifySubscribers",
            "baseName": "notifySubscribers",
            "type": "boolean"
        },
        {
            "name": "boardId",
            "baseName": "boardId",
            "type": "string"
        },
        {
            "name": "altText",
            "baseName": "altText",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PostPlatformSettings.attributeTypeMap;
    }
}

export namespace PostPlatformSettings {
    export enum PostTypeEnum {
        Feed = <any> 'feed',
        Story = <any> 'story',
        Reel = <any> 'reel',
        Carousel = <any> 'carousel'
    }
    export enum ReplyControlEnum {
        Everyone = <any> 'everyone',
        AccountsYouFollow = <any> 'accountsYouFollow',
        MentionedOnly = <any> 'mentionedOnly'
    }
    export enum PrivacyLevelEnum {
        PublicToEveryone = <any> 'publicToEveryone',
        MutualFollowFriends = <any> 'mutualFollowFriends',
        FollowerOfCreator = <any> 'followerOfCreator',
        SelfOnly = <any> 'selfOnly'
    }
    export enum VisibilityEnum {
        Public = <any> 'PUBLIC',
        Connections = <any> 'CONNECTIONS'
    }
    export enum ReplySettingsEnum {
        Following = <any> 'following',
        MentionedUsers = <any> 'mentionedUsers'
    }
    export enum PrivacyStatusEnum {
        Public = <any> 'public',
        Unlisted = <any> 'unlisted',
        Private = <any> 'private'
    }
}
