/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum PublicPlatformOutput {
    Twitter = <any> 'twitter',
    Instagram = <any> 'instagram',
    Tiktok = <any> 'tiktok',
    Linkedin = <any> 'linkedin',
    Facebook = <any> 'facebook',
    Youtube = <any> 'youtube',
    Threads = <any> 'threads',
    Pinterest = <any> 'pinterest'
}
