/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ThreadsSettings {
    'replyControl'?: ThreadsSettings.ReplyControlEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "replyControl",
            "baseName": "replyControl",
            "type": "ThreadsSettings.ReplyControlEnum"
        }    ];

    static getAttributeTypeMap() {
        return ThreadsSettings.attributeTypeMap;
    }
}

export namespace ThreadsSettings {
    export enum ReplyControlEnum {
        Everyone = <any> 'everyone',
        AccountsYouFollow = <any> 'accountsYouFollow',
        MentionedOnly = <any> 'mentionedOnly'
    }
}
