/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TikTokSettings {
    'privacyLevel'?: TikTokSettings.PrivacyLevelEnum;
    'allowComments'?: boolean;
    'allowDuet'?: boolean;
    'allowStitch'?: boolean;
    'disableComment'?: boolean;
    'disableDuet'?: boolean;
    'disableStitch'?: boolean;
    'videoCoverTimestampMs'?: number;
    'uploadAsDraft'?: boolean;
    'brandContentToggle'?: boolean;
    'brandOrganicToggle'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "privacyLevel",
            "baseName": "privacyLevel",
            "type": "TikTokSettings.PrivacyLevelEnum"
        },
        {
            "name": "allowComments",
            "baseName": "allowComments",
            "type": "boolean"
        },
        {
            "name": "allowDuet",
            "baseName": "allowDuet",
            "type": "boolean"
        },
        {
            "name": "allowStitch",
            "baseName": "allowStitch",
            "type": "boolean"
        },
        {
            "name": "disableComment",
            "baseName": "disableComment",
            "type": "boolean"
        },
        {
            "name": "disableDuet",
            "baseName": "disableDuet",
            "type": "boolean"
        },
        {
            "name": "disableStitch",
            "baseName": "disableStitch",
            "type": "boolean"
        },
        {
            "name": "videoCoverTimestampMs",
            "baseName": "videoCoverTimestampMs",
            "type": "number"
        },
        {
            "name": "uploadAsDraft",
            "baseName": "uploadAsDraft",
            "type": "boolean"
        },
        {
            "name": "brandContentToggle",
            "baseName": "brandContentToggle",
            "type": "boolean"
        },
        {
            "name": "brandOrganicToggle",
            "baseName": "brandOrganicToggle",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return TikTokSettings.attributeTypeMap;
    }
}

export namespace TikTokSettings {
    export enum PrivacyLevelEnum {
        PublicToEveryone = <any> 'publicToEveryone',
        MutualFollowFriends = <any> 'mutualFollowFriends',
        FollowerOfCreator = <any> 'followerOfCreator',
        SelfOnly = <any> 'selfOnly'
    }
}
