/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class XSettings {
    'replySettings'?: XSettings.ReplySettingsEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "replySettings",
            "baseName": "replySettings",
            "type": "XSettings.ReplySettingsEnum"
        }    ];

    static getAttributeTypeMap() {
        return XSettings.attributeTypeMap;
    }
}

export namespace XSettings {
    export enum ReplySettingsEnum {
        Following = <any> 'following',
        MentionedUsers = <any> 'mentionedUsers'
    }
}
