/**
 * PostZen Public API
 * The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { YouTubeSettingsTags } from './youTubeSettingsTags';

export class YouTubeSettings {
    'title'?: string;
    'privacyStatus'?: YouTubeSettings.PrivacyStatusEnum;
    'tags'?: YouTubeSettingsTags;
    'categoryId'?: string;
    'madeForKids'?: boolean;
    'notifySubscribers'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "privacyStatus",
            "baseName": "privacyStatus",
            "type": "YouTubeSettings.PrivacyStatusEnum"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "YouTubeSettingsTags"
        },
        {
            "name": "categoryId",
            "baseName": "categoryId",
            "type": "string"
        },
        {
            "name": "madeForKids",
            "baseName": "madeForKids",
            "type": "boolean"
        },
        {
            "name": "notifySubscribers",
            "baseName": "notifySubscribers",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return YouTubeSettings.attributeTypeMap;
    }
}

export namespace YouTubeSettings {
    export enum PrivacyStatusEnum {
        Public = <any> 'public',
        Unlisted = <any> 'unlisted',
        Private = <any> 'private'
    }
}
