/**
 * Auto-generated endpoint tests from OpenAPI spec.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Run `npm run generate:tests` to regenerate.
 */

import { describe, expect, it } from 'vitest';
import PostZen from '../src';

describe('Endpoint Methods', () => {
  const client = new PostZen({ apiKey: 'test_key' });

  describe('profiles', () => {
    it('has createProfile', () => {
      expect(client.profiles.createProfile).toBeDefined();
      expect(client.profiles.createProfile).toBeTypeOf('function');
    });

    it('has deleteProfile', () => {
      expect(client.profiles.deleteProfile).toBeDefined();
      expect(client.profiles.deleteProfile).toBeTypeOf('function');
    });

    it('has getProfile', () => {
      expect(client.profiles.getProfile).toBeDefined();
      expect(client.profiles.getProfile).toBeTypeOf('function');
    });

    it('has listProfiles', () => {
      expect(client.profiles.listProfiles).toBeDefined();
      expect(client.profiles.listProfiles).toBeTypeOf('function');
    });

    it('has updateProfile', () => {
      expect(client.profiles.updateProfile).toBeDefined();
      expect(client.profiles.updateProfile).toBeTypeOf('function');
    });

  });

  describe('accounts', () => {
    it('has disconnectAccount', () => {
      expect(client.accounts.disconnectAccount).toBeDefined();
      expect(client.accounts.disconnectAccount).toBeTypeOf('function');
    });

    it('has listAccounts', () => {
      expect(client.accounts.listAccounts).toBeDefined();
      expect(client.accounts.listAccounts).toBeTypeOf('function');
    });

  });

  describe('connect', () => {
    it('has completeConnect', () => {
      expect(client.connect.completeConnect).toBeDefined();
      expect(client.connect.completeConnect).toBeTypeOf('function');
    });

    it('has createConnectUrl', () => {
      expect(client.connect.createConnectUrl).toBeDefined();
      expect(client.connect.createConnectUrl).toBeTypeOf('function');
    });

  });

  describe('media', () => {
    it('has createMediaPresign', () => {
      expect(client.media.createMediaPresign).toBeDefined();
      expect(client.media.createMediaPresign).toBeTypeOf('function');
    });

  });

  describe('posts', () => {
    it('has createPost', () => {
      expect(client.posts.createPost).toBeDefined();
      expect(client.posts.createPost).toBeTypeOf('function');
    });

    it('has listPosts', () => {
      expect(client.posts.listPosts).toBeDefined();
      expect(client.posts.listPosts).toBeTypeOf('function');
    });

  });

  describe('apikeys', () => {
    it('has createApiKey', () => {
      expect(client.apikeys.createApiKey).toBeDefined();
      expect(client.apikeys.createApiKey).toBeTypeOf('function');
    });

    it('has deleteApiKey', () => {
      expect(client.apikeys.deleteApiKey).toBeDefined();
      expect(client.apikeys.deleteApiKey).toBeTypeOf('function');
    });

    it('has listApiKeys', () => {
      expect(client.apikeys.listApiKeys).toBeDefined();
      expect(client.apikeys.listApiKeys).toBeTypeOf('function');
    });

  });

  describe('analytics', () => {
    it('has getAnalytics', () => {
      expect(client.analytics.getAnalytics).toBeDefined();
      expect(client.analytics.getAnalytics).toBeTypeOf('function');
    });

    it('has getBestTimeToPost', () => {
      expect(client.analytics.getBestTimeToPost).toBeDefined();
      expect(client.analytics.getBestTimeToPost).toBeTypeOf('function');
    });

    it('has getDailyMetrics', () => {
      expect(client.analytics.getDailyMetrics).toBeDefined();
      expect(client.analytics.getDailyMetrics).toBeTypeOf('function');
    });

    it('has getFollowerStats', () => {
      expect(client.analytics.getFollowerStats).toBeDefined();
      expect(client.analytics.getFollowerStats).toBeTypeOf('function');
    });

    it('has getPostTimeline', () => {
      expect(client.analytics.getPostTimeline).toBeDefined();
      expect(client.analytics.getPostTimeline).toBeTypeOf('function');
    });

    it('has syncExternalPosts', () => {
      expect(client.analytics.syncExternalPosts).toBeDefined();
      expect(client.analytics.syncExternalPosts).toBeTypeOf('function');
    });

  });

});
