/**
 * Auto-generated endpoint tests from OpenAPI spec.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Run `npm run generate:tests` to regenerate.
 */

import { describe, expect, it } from 'vitest';
import PostZen from '../src';

describe('Endpoint Methods', () => {
  const client = new PostZen({ apiKey: 'test_key' });

  describe('profiles', () => {
    it('has createProfile', () => {
      expect(client.profiles.createProfile).toBeDefined();
      expect(client.profiles.createProfile).toBeTypeOf('function');
    });

    it('has deleteProfile', () => {
      expect(client.profiles.deleteProfile).toBeDefined();
      expect(client.profiles.deleteProfile).toBeTypeOf('function');
    });

    it('has getProfile', () => {
      expect(client.profiles.getProfile).toBeDefined();
      expect(client.profiles.getProfile).toBeTypeOf('function');
    });

    it('has listProfiles', () => {
      expect(client.profiles.listProfiles).toBeDefined();
      expect(client.profiles.listProfiles).toBeTypeOf('function');
    });

    it('has updateProfile', () => {
      expect(client.profiles.updateProfile).toBeDefined();
      expect(client.profiles.updateProfile).toBeTypeOf('function');
    });

  });

  describe('accounts', () => {
    it('has createPinterestBoard', () => {
      expect(client.accounts.createPinterestBoard).toBeDefined();
      expect(client.accounts.createPinterestBoard).toBeTypeOf('function');
    });

    it('has disconnectAccount', () => {
      expect(client.accounts.disconnectAccount).toBeDefined();
      expect(client.accounts.disconnectAccount).toBeTypeOf('function');
    });

    it('has getPinterestBoards', () => {
      expect(client.accounts.getPinterestBoards).toBeDefined();
      expect(client.accounts.getPinterestBoards).toBeTypeOf('function');
    });

    it('has listAccounts', () => {
      expect(client.accounts.listAccounts).toBeDefined();
      expect(client.accounts.listAccounts).toBeTypeOf('function');
    });

    it('has updatePinterestBoards', () => {
      expect(client.accounts.updatePinterestBoards).toBeDefined();
      expect(client.accounts.updatePinterestBoards).toBeTypeOf('function');
    });

  });

  describe('connect', () => {
    it('has completeConnect', () => {
      expect(client.connect.completeConnect).toBeDefined();
      expect(client.connect.completeConnect).toBeTypeOf('function');
    });

    it('has createConnectUrl', () => {
      expect(client.connect.createConnectUrl).toBeDefined();
      expect(client.connect.createConnectUrl).toBeTypeOf('function');
    });

    it('has listPinterestBoardsForSelection', () => {
      expect(client.connect.listPinterestBoardsForSelection).toBeDefined();
      expect(client.connect.listPinterestBoardsForSelection).toBeTypeOf('function');
    });

    it('has selectPinterestBoard', () => {
      expect(client.connect.selectPinterestBoard).toBeDefined();
      expect(client.connect.selectPinterestBoard).toBeTypeOf('function');
    });

  });

  describe('media', () => {
    it('has createMediaPresign', () => {
      expect(client.media.createMediaPresign).toBeDefined();
      expect(client.media.createMediaPresign).toBeTypeOf('function');
    });

    it('has uploadMediaDirect', () => {
      expect(client.media.uploadMediaDirect).toBeDefined();
      expect(client.media.uploadMediaDirect).toBeTypeOf('function');
    });

  });

  describe('posts', () => {
    it('has bulkUploadPosts', () => {
      expect(client.posts.bulkUploadPosts).toBeDefined();
      expect(client.posts.bulkUploadPosts).toBeTypeOf('function');
    });

    it('has createPost', () => {
      expect(client.posts.createPost).toBeDefined();
      expect(client.posts.createPost).toBeTypeOf('function');
    });

    it('has deletePost', () => {
      expect(client.posts.deletePost).toBeDefined();
      expect(client.posts.deletePost).toBeTypeOf('function');
    });

    it('has getPost', () => {
      expect(client.posts.getPost).toBeDefined();
      expect(client.posts.getPost).toBeTypeOf('function');
    });

    it('has listPostComments', () => {
      expect(client.posts.listPostComments).toBeDefined();
      expect(client.posts.listPostComments).toBeTypeOf('function');
    });

    it('has listPostReactions', () => {
      expect(client.posts.listPostReactions).toBeDefined();
      expect(client.posts.listPostReactions).toBeTypeOf('function');
    });

    it('has listPosts', () => {
      expect(client.posts.listPosts).toBeDefined();
      expect(client.posts.listPosts).toBeTypeOf('function');
    });

    it('has updatePost', () => {
      expect(client.posts.updatePost).toBeDefined();
      expect(client.posts.updatePost).toBeTypeOf('function');
    });

  });

  describe('apikeys', () => {
    it('has createApiKey', () => {
      expect(client.apikeys.createApiKey).toBeDefined();
      expect(client.apikeys.createApiKey).toBeTypeOf('function');
    });

    it('has deleteApiKey', () => {
      expect(client.apikeys.deleteApiKey).toBeDefined();
      expect(client.apikeys.deleteApiKey).toBeTypeOf('function');
    });

    it('has listApiKeys', () => {
      expect(client.apikeys.listApiKeys).toBeDefined();
      expect(client.apikeys.listApiKeys).toBeTypeOf('function');
    });

  });

  describe('commentautomations', () => {
    it('has createCommentAutomation', () => {
      expect(client.commentautomations.createCommentAutomation).toBeDefined();
      expect(client.commentautomations.createCommentAutomation).toBeTypeOf('function');
    });

    it('has deleteCommentAutomation', () => {
      expect(client.commentautomations.deleteCommentAutomation).toBeDefined();
      expect(client.commentautomations.deleteCommentAutomation).toBeTypeOf('function');
    });

    it('has getCommentAutomation', () => {
      expect(client.commentautomations.getCommentAutomation).toBeDefined();
      expect(client.commentautomations.getCommentAutomation).toBeTypeOf('function');
    });

    it('has listCommentAutomationLogs', () => {
      expect(client.commentautomations.listCommentAutomationLogs).toBeDefined();
      expect(client.commentautomations.listCommentAutomationLogs).toBeTypeOf('function');
    });

    it('has listCommentAutomations', () => {
      expect(client.commentautomations.listCommentAutomations).toBeDefined();
      expect(client.commentautomations.listCommentAutomations).toBeTypeOf('function');
    });

    it('has updateCommentAutomation', () => {
      expect(client.commentautomations.updateCommentAutomation).toBeDefined();
      expect(client.commentautomations.updateCommentAutomation).toBeTypeOf('function');
    });

  });

  describe('queues', () => {
    it('has createQueueSlot', () => {
      expect(client.queues.createQueueSlot).toBeDefined();
      expect(client.queues.createQueueSlot).toBeTypeOf('function');
    });

    it('has deleteQueueSlot', () => {
      expect(client.queues.deleteQueueSlot).toBeDefined();
      expect(client.queues.deleteQueueSlot).toBeTypeOf('function');
    });

    it('has getNextQueueSlot', () => {
      expect(client.queues.getNextQueueSlot).toBeDefined();
      expect(client.queues.getNextQueueSlot).toBeTypeOf('function');
    });

    it('has listQueueSlots', () => {
      expect(client.queues.listQueueSlots).toBeDefined();
      expect(client.queues.listQueueSlots).toBeTypeOf('function');
    });

    it('has previewQueue', () => {
      expect(client.queues.previewQueue).toBeDefined();
      expect(client.queues.previewQueue).toBeTypeOf('function');
    });

    it('has updateQueueSlot', () => {
      expect(client.queues.updateQueueSlot).toBeDefined();
      expect(client.queues.updateQueueSlot).toBeTypeOf('function');
    });

  });

  describe('webhooks', () => {
    it('has createWebhook', () => {
      expect(client.webhooks.createWebhook).toBeDefined();
      expect(client.webhooks.createWebhook).toBeTypeOf('function');
    });

    it('has deleteWebhook', () => {
      expect(client.webhooks.deleteWebhook).toBeDefined();
      expect(client.webhooks.deleteWebhook).toBeTypeOf('function');
    });

    it('has getWebhook', () => {
      expect(client.webhooks.getWebhook).toBeDefined();
      expect(client.webhooks.getWebhook).toBeTypeOf('function');
    });

    it('has listWebhookDeliveries', () => {
      expect(client.webhooks.listWebhookDeliveries).toBeDefined();
      expect(client.webhooks.listWebhookDeliveries).toBeTypeOf('function');
    });

    it('has listWebhooks', () => {
      expect(client.webhooks.listWebhooks).toBeDefined();
      expect(client.webhooks.listWebhooks).toBeTypeOf('function');
    });

    it('has redeliverWebhookDelivery', () => {
      expect(client.webhooks.redeliverWebhookDelivery).toBeDefined();
      expect(client.webhooks.redeliverWebhookDelivery).toBeTypeOf('function');
    });

    it('has testWebhook', () => {
      expect(client.webhooks.testWebhook).toBeDefined();
      expect(client.webhooks.testWebhook).toBeTypeOf('function');
    });

    it('has updateWebhook', () => {
      expect(client.webhooks.updateWebhook).toBeDefined();
      expect(client.webhooks.updateWebhook).toBeTypeOf('function');
    });

  });

  describe('inbox', () => {
    it('has deleteInboxComment', () => {
      expect(client.inbox.deleteInboxComment).toBeDefined();
      expect(client.inbox.deleteInboxComment).toBeTypeOf('function');
    });

    it('has getInboxConversation', () => {
      expect(client.inbox.getInboxConversation).toBeDefined();
      expect(client.inbox.getInboxConversation).toBeTypeOf('function');
    });

    it('has hideInboxComment', () => {
      expect(client.inbox.hideInboxComment).toBeDefined();
      expect(client.inbox.hideInboxComment).toBeTypeOf('function');
    });

    it('has listInboxConversationMessages', () => {
      expect(client.inbox.listInboxConversationMessages).toBeDefined();
      expect(client.inbox.listInboxConversationMessages).toBeTypeOf('function');
    });

    it('has listInboxConversations', () => {
      expect(client.inbox.listInboxConversations).toBeDefined();
      expect(client.inbox.listInboxConversations).toBeTypeOf('function');
    });

    it('has listInboxPostComments', () => {
      expect(client.inbox.listInboxPostComments).toBeDefined();
      expect(client.inbox.listInboxPostComments).toBeTypeOf('function');
    });

    it('has markInboxConversationRead', () => {
      expect(client.inbox.markInboxConversationRead).toBeDefined();
      expect(client.inbox.markInboxConversationRead).toBeTypeOf('function');
    });

    it('has replyToInboxPost', () => {
      expect(client.inbox.replyToInboxPost).toBeDefined();
      expect(client.inbox.replyToInboxPost).toBeTypeOf('function');
    });

    it('has searchInboxConversations', () => {
      expect(client.inbox.searchInboxConversations).toBeDefined();
      expect(client.inbox.searchInboxConversations).toBeTypeOf('function');
    });

    it('has sendInboxMessage', () => {
      expect(client.inbox.sendInboxMessage).toBeDefined();
      expect(client.inbox.sendInboxMessage).toBeTypeOf('function');
    });

    it('has unhideInboxComment', () => {
      expect(client.inbox.unhideInboxComment).toBeDefined();
      expect(client.inbox.unhideInboxComment).toBeTypeOf('function');
    });

    it('has updateInboxConversation', () => {
      expect(client.inbox.updateInboxConversation).toBeDefined();
      expect(client.inbox.updateInboxConversation).toBeTypeOf('function');
    });

  });

  describe('analytics', () => {
    it('has getAnalytics', () => {
      expect(client.analytics.getAnalytics).toBeDefined();
      expect(client.analytics.getAnalytics).toBeTypeOf('function');
    });

    it('has getBestTimeToPost', () => {
      expect(client.analytics.getBestTimeToPost).toBeDefined();
      expect(client.analytics.getBestTimeToPost).toBeTypeOf('function');
    });

    it('has getDailyMetrics', () => {
      expect(client.analytics.getDailyMetrics).toBeDefined();
      expect(client.analytics.getDailyMetrics).toBeTypeOf('function');
    });

    it('has getFollowerStats', () => {
      expect(client.analytics.getFollowerStats).toBeDefined();
      expect(client.analytics.getFollowerStats).toBeTypeOf('function');
    });

    it('has getPostTimeline', () => {
      expect(client.analytics.getPostTimeline).toBeDefined();
      expect(client.analytics.getPostTimeline).toBeTypeOf('function');
    });

    it('has syncExternalPosts', () => {
      expect(client.analytics.syncExternalPosts).toBeDefined();
      expect(client.analytics.syncExternalPosts).toBeTypeOf('function');
    });

  });

});
