/**
 * Auto-generated endpoint tests from OpenAPI spec.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Run `npm run generate:tests` to regenerate.
 */

import { describe, expect, it } from 'vitest';
import PostZen from '../src';

describe('Endpoint Methods', () => {
  const client = new PostZen({ apiKey: 'test_key' });

  describe('profiles', () => {
    it('has createProfile', () => {
      expect(client.profiles.createProfile).toBeDefined();
      expect(client.profiles.createProfile).toBeTypeOf('function');
    });

    it('has deleteProfile', () => {
      expect(client.profiles.deleteProfile).toBeDefined();
      expect(client.profiles.deleteProfile).toBeTypeOf('function');
    });

    it('has getProfile', () => {
      expect(client.profiles.getProfile).toBeDefined();
      expect(client.profiles.getProfile).toBeTypeOf('function');
    });

    it('has listProfiles', () => {
      expect(client.profiles.listProfiles).toBeDefined();
      expect(client.profiles.listProfiles).toBeTypeOf('function');
    });

    it('has updateProfile', () => {
      expect(client.profiles.updateProfile).toBeDefined();
      expect(client.profiles.updateProfile).toBeTypeOf('function');
    });

  });

  describe('accounts', () => {
    it('has disconnectAccount', () => {
      expect(client.accounts.disconnectAccount).toBeDefined();
      expect(client.accounts.disconnectAccount).toBeTypeOf('function');
    });

    it('has listAccounts', () => {
      expect(client.accounts.listAccounts).toBeDefined();
      expect(client.accounts.listAccounts).toBeTypeOf('function');
    });

  });

  describe('connect', () => {
    it('has completeConnect', () => {
      expect(client.connect.completeConnect).toBeDefined();
      expect(client.connect.completeConnect).toBeTypeOf('function');
    });

    it('has createConnectUrl', () => {
      expect(client.connect.createConnectUrl).toBeDefined();
      expect(client.connect.createConnectUrl).toBeTypeOf('function');
    });

  });

  describe('media', () => {
    it('has createMediaPresign', () => {
      expect(client.media.createMediaPresign).toBeDefined();
      expect(client.media.createMediaPresign).toBeTypeOf('function');
    });

  });

  describe('posts', () => {
    it('has createPost', () => {
      expect(client.posts.createPost).toBeDefined();
      expect(client.posts.createPost).toBeTypeOf('function');
    });

  });

});
