import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

interface OpenAPISpec {
  paths: Record<string, PathItem>;
}

interface PathItem {
  parameters?: ParameterObject[];
  [method: string]: OperationObject | ParameterObject[] | undefined;
}

interface ParameterObject {
  name: string;
  in: string;
  required?: boolean;
}

interface OperationObject {
  tags?: string[];
  operationId?: string;
  summary?: string;
}

interface OperationInfo {
  namespace: string;
  functionName: string;
  methodName: string;
  path: string;
  method: string;
  summary?: string;
}

const RESOURCE_ORDER = ['profiles', 'accounts', 'connect', 'media', 'posts'];
const HTTP_METHODS = new Set(['get', 'post', 'put', 'patch', 'delete']);

function tagToNamespace(tag: string): string {
  return tag.toLowerCase().replace(/[^a-z0-9]+/g, '');
}

function getOperations(spec: OpenAPISpec): OperationInfo[] {
  const operations: OperationInfo[] = [];

  for (const [pathStr, pathItem] of Object.entries(spec.paths ?? {})) {
    for (const [method, maybeOperation] of Object.entries(pathItem)) {
      if (!HTTP_METHODS.has(method) || !maybeOperation || Array.isArray(maybeOperation)) {
        continue;
      }

      const operation = maybeOperation as OperationObject;
      if (!operation.operationId) {
        continue;
      }

      const tag = operation.tags?.[0] ?? 'other';
      const namespace = tagToNamespace(tag);

      operations.push({
        namespace,
        functionName: operation.operationId,
        methodName: operation.operationId,
        path: pathStr,
        method,
        summary: operation.summary,
      });
    }
  }

  return operations;
}

function sortOperations(operations: OperationInfo[]): OperationInfo[] {
  const resourceRank = new Map(RESOURCE_ORDER.map((resource, index) => [resource, index]));

  return [...operations].sort((a, b) => {
    const aRank = resourceRank.get(a.namespace) ?? Number.MAX_SAFE_INTEGER;
    const bRank = resourceRank.get(b.namespace) ?? Number.MAX_SAFE_INTEGER;

    if (aRank !== bRank) {
      return aRank - bRank;
    }

    return a.methodName.localeCompare(b.methodName);
  });
}

function groupByNamespace(operations: OperationInfo[]): Map<string, OperationInfo[]> {
  const grouped = new Map<string, OperationInfo[]>();

  for (const operation of sortOperations(operations)) {
    const group = grouped.get(operation.namespace) ?? [];
    group.push(operation);
    grouped.set(operation.namespace, group);
  }

  return grouped;
}

function namespaceComment(namespace: string): string {
  const comments: Record<string, string> = {
    profiles: 'Profiles API - Manage workspace profiles',
    accounts: 'Accounts API - Manage connected social accounts',
    connect: 'Connect API - OAuth connection flows',
    media: 'Media API - Create presigned media uploads',
    posts: 'Posts API - Create, schedule, and publish posts',
  };

  return comments[namespace] ?? `${namespace} API`;
}

function generateNamespace(namespace: string, operations: OperationInfo[]): string {
  const lines = [
    '  /**',
    `   * ${namespaceComment(namespace)}`,
    '   */',
    `  ${namespace} = {`,
  ];

  for (const operation of operations) {
    lines.push(
      `    ${operation.methodName}: ((options?: Parameters<typeof ${operation.functionName}>[0]) => ${operation.functionName}(this._withRequestOptions(options) as Parameters<typeof ${operation.functionName}>[0])) as typeof ${operation.functionName},`
    );
  }

  lines.push('  };');
  return lines.join('\n');
}

function generateClientCode(grouped: Map<string, OperationInfo[]>): string {
  const functions = [...grouped.values()]
    .flat()
    .map((operation) => operation.functionName)
    .sort();

  const namespaceBlocks = [...grouped.entries()]
    .map(([namespace, operations]) => generateNamespace(namespace, operations))
    .join('\n\n');

  return `/**
 * This file is generated by scripts/generate-client.ts.
 * Do not edit this file by hand.
 */

import packageJson from '../package.json';
import { createClient, createConfig, type Client } from './generated/client';
import {
${functions.map((fn) => `  ${fn},`).join('\n')}
} from './generated/sdk.gen';
import { PostZenApiError, parseApiError } from './errors';

export interface ClientOptions {
  /**
   * API key for authentication. Defaults to process.env.POSTZEN_API_KEY.
   */
  apiKey?: string | undefined;

  /**
   * Override the default API base URL.
   * @default "https://api.postzen.dev"
   */
  baseURL?: string | null | undefined;

  /**
   * Maximum request time in milliseconds.
   * @default 60000
   */
  timeout?: number | undefined;

  /**
   * Default headers sent with every API request.
   */
  defaultHeaders?: Record<string, string> | undefined;
}

type FetchFn = (request: Request) => ReturnType<typeof fetch>;

type RequestOptions = {
  signal?: AbortSignal | null;
  fetch?: FetchFn;
  client?: Client;
};

function getAbortReason(signal: AbortSignal): unknown {
  return signal.reason ?? new DOMException('The operation was aborted.', 'AbortError');
}

function abortError(): DOMException {
  return new DOMException('The operation timed out.', 'TimeoutError');
}

function createTimeoutSignal(timeout: number): AbortSignal | undefined {
  if (!Number.isFinite(timeout) || timeout <= 0) {
    return undefined;
  }

  const abortSignal = AbortSignal as typeof AbortSignal & {
    timeout?: (milliseconds: number) => AbortSignal;
  };

  if (typeof abortSignal.timeout === 'function') {
    return abortSignal.timeout(timeout);
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(abortError()), timeout);
  const unref = (timer as { unref?: () => void }).unref;

  if (typeof unref === 'function') {
    unref.call(timer);
  }

  return controller.signal;
}

function mergeSignals(signals: Array<AbortSignal | undefined>): AbortSignal | undefined {
  const activeSignals = signals.filter((signal): signal is AbortSignal => Boolean(signal));

  if (activeSignals.length === 0) {
    return undefined;
  }

  if (activeSignals.length === 1) {
    return activeSignals[0];
  }

  const alreadyAborted = activeSignals.find((signal) => signal.aborted);

  if (alreadyAborted) {
    const controller = new AbortController();
    controller.abort(getAbortReason(alreadyAborted));
    return controller.signal;
  }

  const abortSignal = AbortSignal as typeof AbortSignal & {
    any?: (signals: AbortSignal[]) => AbortSignal;
  };

  if (typeof abortSignal.any === 'function') {
    return abortSignal.any(activeSignals);
  }

  const controller = new AbortController();
  const onAbort = (event: Event) => {
    const signal = event.target as AbortSignal;
    controller.abort(getAbortReason(signal));

    for (const activeSignal of activeSignals) {
      activeSignal.removeEventListener('abort', onAbort);
    }
  };

  for (const signal of activeSignals) {
    signal.addEventListener('abort', onAbort, { once: true });
  }

  return controller.signal;
}

function raceWithAbort<T>(promise: Promise<T>, signal?: AbortSignal): Promise<T> {
  if (!signal) {
    return promise;
  }

  if (signal.aborted) {
    return Promise.reject(getAbortReason(signal));
  }

  return new Promise<T>((resolve, reject) => {
    const onAbort = () => {
      reject(getAbortReason(signal));
    };

    signal.addEventListener('abort', onAbort, { once: true });
    promise.then(
      (value) => {
        signal.removeEventListener('abort', onAbort);
        resolve(value);
      },
      (error: unknown) => {
        signal.removeEventListener('abort', onAbort);
        reject(error);
      }
    );
  });
}

/**
 * API client for the PostZen Public API.
 */
export class PostZen {
  private readonly _client!: Client;
  private readonly _timeout!: number;

  /**
   * API key used for authentication.
   */
  apiKey!: string;

  /**
   * Base URL for API requests.
   */
  baseURL!: string;

${namespaceBlocks}

  constructor(options: ClientOptions = {}) {
    const apiKey = options.apiKey ?? process.env.POSTZEN_API_KEY;

    if (!apiKey) {
      throw new PostZenApiError(
        "The POSTZEN_API_KEY environment variable is missing or empty. Provide it in the environment or instantiate the client with new PostZen({ apiKey: 'pzn_live_...' }).",
        401,
        'missing_api_key'
      );
    }

    this.apiKey = apiKey;
    this.baseURL = options.baseURL ?? 'https://api.postzen.dev';
    this._timeout = options.timeout ?? 60000;
    this._client = createClient(
      createConfig({
        baseUrl: this.baseURL,
        headers: {
          'User-Agent': \`postzen-node/\${packageJson.version}\`,
          ...(options.defaultHeaders ?? {}),
        },
      })
    );

    this._client.interceptors.request.use((request: Request) => {
      request.headers.set('Authorization', \`Bearer \${this.apiKey}\`);
      return request;
    });

    this._client.interceptors.response.use(async (response: Response) => {
      if (response.ok) {
        return response;
      }

      let body: Record<string, unknown> | undefined;

      try {
        body = (await response.clone().json()) as Record<string, unknown>;
      } catch {
        body = undefined;
      }

      throw parseApiError(response, body);
    });
  }

  private _withRequestOptions(options?: RequestOptions): RequestOptions & { client: Client } {
    const requestOptions = {
      ...(options ?? {}),
    } as RequestOptions & { client: Client };
    const timeoutSignal = createTimeoutSignal(this._timeout);
    const callerSignal = options?.signal ?? undefined;

    requestOptions.client = this._client;
    requestOptions.signal = mergeSignals([callerSignal, timeoutSignal]);

    if (options?.fetch) {
      requestOptions.fetch = this._wrapFetch(options.fetch);
    }

    return requestOptions;
  }

  private _wrapFetch(fetchImpl: FetchFn): FetchFn {
    return (request: Request) => {
      return raceWithAbort(fetchImpl(request), request.signal ?? undefined);
    };
  }
}

export default PostZen;
`;
}

function main(): void {
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  const specPath = resolve(scriptDir, '..', 'openapi.json');
  const outputPath = resolve(scriptDir, '..', 'src', 'client.ts');
  const spec = JSON.parse(readFileSync(specPath, 'utf8')) as OpenAPISpec;
  const grouped = groupByNamespace(getOperations(spec));
  const clientCode = generateClientCode(grouped);

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, clientCode);

  console.log(`Generated ${outputPath}`);
  for (const [namespace, operations] of grouped.entries()) {
    console.log(`  - ${namespace}: ${operations.length} methods`);
  }
}

main();
