import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

interface OpenAPISpec {
  paths: Record<string, Record<string, OperationObject | ParameterObject[] | undefined>>;
}

interface ParameterObject {
  name: string;
  in: string;
}

interface OperationObject {
  tags?: string[];
  operationId?: string;
}

interface Endpoint {
  resource: string;
  method: string;
}

const RESOURCE_ORDER = ['profiles', 'accounts', 'connect', 'media', 'posts'];
const HTTP_METHODS = new Set(['get', 'post', 'put', 'patch', 'delete']);

function tagToResourceKey(tag: string): string {
  return tag.toLowerCase().replace(/[^a-z0-9]+/g, '');
}

function extractEndpoints(spec: OpenAPISpec): Endpoint[] {
  const endpoints: Endpoint[] = [];

  for (const pathItem of Object.values(spec.paths ?? {})) {
    for (const [method, maybeOperation] of Object.entries(pathItem)) {
      if (!HTTP_METHODS.has(method) || !maybeOperation || Array.isArray(maybeOperation)) {
        continue;
      }

      const operation = maybeOperation as OperationObject;
      const operationId = operation.operationId;
      const tag = operation.tags?.[0];

      if (!operationId || !tag) {
        continue;
      }

      endpoints.push({
        resource: tagToResourceKey(tag),
        method: operationId,
      });
    }
  }

  return endpoints.sort((a, b) => {
    const aRank = RESOURCE_ORDER.indexOf(a.resource);
    const bRank = RESOURCE_ORDER.indexOf(b.resource);
    const normalizedARank = aRank === -1 ? Number.MAX_SAFE_INTEGER : aRank;
    const normalizedBRank = bRank === -1 ? Number.MAX_SAFE_INTEGER : bRank;

    if (normalizedARank !== normalizedBRank) {
      return normalizedARank - normalizedBRank;
    }

    return a.method.localeCompare(b.method);
  });
}

function generateTestFile(endpoints: Endpoint[]): string {
  const byResource = new Map<string, Endpoint[]>();

  for (const endpoint of endpoints) {
    const group = byResource.get(endpoint.resource) ?? [];
    group.push(endpoint);
    byResource.set(endpoint.resource, group);
  }

  const lines = [
    '/**',
    ' * Auto-generated endpoint tests from OpenAPI spec.',
    ' *',
    ' * DO NOT EDIT THIS FILE MANUALLY.',
    ' * Run `npm run generate:tests` to regenerate.',
    ' */',
    '',
    "import { describe, expect, it } from 'vitest';",
    "import PostZen from '../src';",
    '',
    "describe('Endpoint Methods', () => {",
    "  const client = new PostZen({ apiKey: 'test_key' });",
    '',
  ];

  for (const [resource, resourceEndpoints] of byResource.entries()) {
    lines.push(`  describe('${resource}', () => {`);

    for (const endpoint of resourceEndpoints) {
      lines.push(`    it('has ${endpoint.method}', () => {`);
      lines.push(`      expect(client.${resource}.${endpoint.method}).toBeDefined();`);
      lines.push(`      expect(client.${resource}.${endpoint.method}).toBeTypeOf('function');`);
      lines.push('    });');
      lines.push('');
    }

    lines.push('  });');
    lines.push('');
  }

  lines.push('});');
  lines.push('');

  return lines.join('\n');
}

function main(): void {
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  const repoRoot = resolve(scriptDir, '..');
  const specPath = resolve(repoRoot, 'openapi.json');
  const outputPath = resolve(repoRoot, 'tests', 'endpoints.test.ts');
  const spec = JSON.parse(readFileSync(specPath, 'utf8')) as OpenAPISpec;
  const endpoints = extractEndpoints(spec);
  const testFile = generateTestFile(endpoints);

  if (process.argv.includes('--print')) {
    console.log(testFile);
    return;
  }

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, testFile);
  console.log(`Generated ${outputPath}`);
  console.log(`Total endpoints: ${endpoints.length}`);
}

main();
