/**
 * This file is generated by scripts/generate-client.ts.
 * Do not edit this file by hand.
 */

import packageJson from '../package.json';
import { createClient, createConfig, type Client } from './generated/client';
import {
  completeConnect,
  createConnectUrl,
  createMediaPresign,
  createPost,
  createProfile,
  deleteProfile,
  disconnectAccount,
  getProfile,
  listAccounts,
  listProfiles,
  updateProfile,
} from './generated/sdk.gen';
import { PostZenApiError, parseApiError } from './errors';

export interface ClientOptions {
  /**
   * API key for authentication. Defaults to process.env.POSTZEN_API_KEY.
   */
  apiKey?: string | undefined;

  /**
   * Override the default API base URL.
   * @default "https://api.postzen.dev"
   */
  baseURL?: string | null | undefined;

  /**
   * Maximum request time in milliseconds.
   * @default 60000
   */
  timeout?: number | undefined;

  /**
   * Default headers sent with every API request.
   */
  defaultHeaders?: Record<string, string> | undefined;
}

type FetchFn = (request: Request) => ReturnType<typeof fetch>;

type RequestOptions = {
  signal?: AbortSignal | null;
  fetch?: FetchFn;
  client?: Client;
};

function getAbortReason(signal: AbortSignal): unknown {
  return signal.reason ?? new DOMException('The operation was aborted.', 'AbortError');
}

function abortError(): DOMException {
  return new DOMException('The operation timed out.', 'TimeoutError');
}

function createTimeoutSignal(timeout: number): AbortSignal | undefined {
  if (!Number.isFinite(timeout) || timeout <= 0) {
    return undefined;
  }

  const abortSignal = AbortSignal as typeof AbortSignal & {
    timeout?: (milliseconds: number) => AbortSignal;
  };

  if (typeof abortSignal.timeout === 'function') {
    return abortSignal.timeout(timeout);
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(abortError()), timeout);
  const unref = (timer as { unref?: () => void }).unref;

  if (typeof unref === 'function') {
    unref.call(timer);
  }

  return controller.signal;
}

function mergeSignals(signals: Array<AbortSignal | undefined>): AbortSignal | undefined {
  const activeSignals = signals.filter((signal): signal is AbortSignal => Boolean(signal));

  if (activeSignals.length === 0) {
    return undefined;
  }

  if (activeSignals.length === 1) {
    return activeSignals[0];
  }

  const alreadyAborted = activeSignals.find((signal) => signal.aborted);

  if (alreadyAborted) {
    const controller = new AbortController();
    controller.abort(getAbortReason(alreadyAborted));
    return controller.signal;
  }

  const abortSignal = AbortSignal as typeof AbortSignal & {
    any?: (signals: AbortSignal[]) => AbortSignal;
  };

  if (typeof abortSignal.any === 'function') {
    return abortSignal.any(activeSignals);
  }

  const controller = new AbortController();
  const onAbort = (event: Event) => {
    const signal = event.target as AbortSignal;
    controller.abort(getAbortReason(signal));

    for (const activeSignal of activeSignals) {
      activeSignal.removeEventListener('abort', onAbort);
    }
  };

  for (const signal of activeSignals) {
    signal.addEventListener('abort', onAbort, { once: true });
  }

  return controller.signal;
}

function raceWithAbort<T>(promise: Promise<T>, signal?: AbortSignal): Promise<T> {
  if (!signal) {
    return promise;
  }

  if (signal.aborted) {
    return Promise.reject(getAbortReason(signal));
  }

  return new Promise<T>((resolve, reject) => {
    const onAbort = () => {
      reject(getAbortReason(signal));
    };

    signal.addEventListener('abort', onAbort, { once: true });
    promise.then(
      (value) => {
        signal.removeEventListener('abort', onAbort);
        resolve(value);
      },
      (error: unknown) => {
        signal.removeEventListener('abort', onAbort);
        reject(error);
      }
    );
  });
}

/**
 * API client for the PostZen Public API.
 */
export class PostZen {
  private readonly _client!: Client;
  private readonly _timeout!: number;

  /**
   * API key used for authentication.
   */
  apiKey!: string;

  /**
   * Base URL for API requests.
   */
  baseURL!: string;

  /**
   * Profiles API - Manage workspace profiles
   */
  profiles = {
    createProfile: ((options?: Parameters<typeof createProfile>[0]) => createProfile(this._withRequestOptions(options) as Parameters<typeof createProfile>[0])) as typeof createProfile,
    deleteProfile: ((options?: Parameters<typeof deleteProfile>[0]) => deleteProfile(this._withRequestOptions(options) as Parameters<typeof deleteProfile>[0])) as typeof deleteProfile,
    getProfile: ((options?: Parameters<typeof getProfile>[0]) => getProfile(this._withRequestOptions(options) as Parameters<typeof getProfile>[0])) as typeof getProfile,
    listProfiles: ((options?: Parameters<typeof listProfiles>[0]) => listProfiles(this._withRequestOptions(options) as Parameters<typeof listProfiles>[0])) as typeof listProfiles,
    updateProfile: ((options?: Parameters<typeof updateProfile>[0]) => updateProfile(this._withRequestOptions(options) as Parameters<typeof updateProfile>[0])) as typeof updateProfile,
  };

  /**
   * Accounts API - Manage connected social accounts
   */
  accounts = {
    disconnectAccount: ((options?: Parameters<typeof disconnectAccount>[0]) => disconnectAccount(this._withRequestOptions(options) as Parameters<typeof disconnectAccount>[0])) as typeof disconnectAccount,
    listAccounts: ((options?: Parameters<typeof listAccounts>[0]) => listAccounts(this._withRequestOptions(options) as Parameters<typeof listAccounts>[0])) as typeof listAccounts,
  };

  /**
   * Connect API - OAuth connection flows
   */
  connect = {
    completeConnect: ((options?: Parameters<typeof completeConnect>[0]) => completeConnect(this._withRequestOptions(options) as Parameters<typeof completeConnect>[0])) as typeof completeConnect,
    createConnectUrl: ((options?: Parameters<typeof createConnectUrl>[0]) => createConnectUrl(this._withRequestOptions(options) as Parameters<typeof createConnectUrl>[0])) as typeof createConnectUrl,
  };

  /**
   * Media API - Create presigned media uploads
   */
  media = {
    createMediaPresign: ((options?: Parameters<typeof createMediaPresign>[0]) => createMediaPresign(this._withRequestOptions(options) as Parameters<typeof createMediaPresign>[0])) as typeof createMediaPresign,
  };

  /**
   * Posts API - Create, schedule, and publish posts
   */
  posts = {
    createPost: ((options?: Parameters<typeof createPost>[0]) => createPost(this._withRequestOptions(options) as Parameters<typeof createPost>[0])) as typeof createPost,
  };

  constructor(options: ClientOptions = {}) {
    const apiKey = options.apiKey ?? process.env.POSTZEN_API_KEY;

    if (!apiKey) {
      throw new PostZenApiError(
        "The POSTZEN_API_KEY environment variable is missing or empty. Provide it in the environment or instantiate the client with new PostZen({ apiKey: 'pzn_live_...' }).",
        401,
        'missing_api_key'
      );
    }

    this.apiKey = apiKey;
    this.baseURL = options.baseURL ?? 'https://api.postzen.dev';
    this._timeout = options.timeout ?? 60000;
    this._client = createClient(
      createConfig({
        baseUrl: this.baseURL,
        headers: {
          'User-Agent': `postzen-node/${packageJson.version}`,
          ...(options.defaultHeaders ?? {}),
        },
      })
    );

    this._client.interceptors.request.use((request: Request) => {
      request.headers.set('Authorization', `Bearer ${this.apiKey}`);
      return request;
    });

    this._client.interceptors.response.use(async (response: Response) => {
      if (response.ok) {
        return response;
      }

      let body: Record<string, unknown> | undefined;

      try {
        body = (await response.clone().json()) as Record<string, unknown>;
      } catch {
        body = undefined;
      }

      throw parseApiError(response, body);
    });
  }

  private _withRequestOptions(options?: RequestOptions): RequestOptions & { client: Client } {
    const requestOptions = {
      ...(options ?? {}),
    } as RequestOptions & { client: Client };
    const timeoutSignal = createTimeoutSignal(this._timeout);
    const callerSignal = options?.signal ?? undefined;

    requestOptions.client = this._client;
    requestOptions.signal = mergeSignals([callerSignal, timeoutSignal]);

    if (options?.fetch) {
      requestOptions.fetch = this._wrapFetch(options.fetch);
    }

    return requestOptions;
  }

  private _wrapFetch(fetchImpl: FetchFn): FetchFn {
    return (request: Request) => {
      return raceWithAbort(fetchImpl(request), request.signal ?? undefined);
    };
  }
}

export default PostZen;
