/**
 * This file is generated by scripts/generate-client.ts.
 * Do not edit this file by hand.
 */

import packageJson from '../package.json';
import { createClient, createConfig, type Client } from './generated/client';
import {
  bulkUploadPosts,
  completeConnect,
  createApiKey,
  createCommentAutomation,
  createConnectUrl,
  createMediaPresign,
  createPinterestBoard,
  createPost,
  createProfile,
  createQueueSlot,
  createWebhook,
  deleteApiKey,
  deleteCommentAutomation,
  deleteInboxComment,
  deletePost,
  deleteProfile,
  deleteQueueSlot,
  deleteWebhook,
  disconnectAccount,
  getAnalytics,
  getBestTimeToPost,
  getCommentAutomation,
  getDailyMetrics,
  getFollowerStats,
  getInboxConversation,
  getNextQueueSlot,
  getPinterestBoards,
  getPost,
  getPostTimeline,
  getProfile,
  getWebhook,
  hideInboxComment,
  listAccounts,
  listApiKeys,
  listCommentAutomationLogs,
  listCommentAutomations,
  listInboxConversationMessages,
  listInboxConversations,
  listInboxPostComments,
  listPinterestBoardsForSelection,
  listPostComments,
  listPostReactions,
  listPosts,
  listProfiles,
  listQueueSlots,
  listWebhookDeliveries,
  listWebhooks,
  markInboxConversationRead,
  previewQueue,
  redeliverWebhookDelivery,
  replyToInboxPost,
  searchInboxConversations,
  selectPinterestBoard,
  sendInboxMessage,
  syncExternalPosts,
  testWebhook,
  unhideInboxComment,
  updateCommentAutomation,
  updateInboxConversation,
  updatePinterestBoards,
  updatePost,
  updateProfile,
  updateQueueSlot,
  updateWebhook,
  uploadMediaDirect,
} from './generated/sdk.gen';
import { PostZenApiError, parseApiError } from './errors';
import {
  uploadMedia,
  type MediaUploadSource,
  type MediaUploadOptions,
  type UploadedMedia,
} from './upload';

export interface ClientOptions {
  /**
   * API key for authentication. Defaults to process.env.POSTZEN_API_KEY.
   */
  apiKey?: string | undefined;

  /**
   * Override the default API base URL.
   * @default "https://api.postzen.dev"
   */
  baseURL?: string | null | undefined;

  /**
   * Maximum request time in milliseconds.
   * @default 60000
   */
  timeout?: number | undefined;

  /**
   * Default headers sent with every API request.
   */
  defaultHeaders?: Record<string, string> | undefined;
}

type FetchFn = (request: Request) => ReturnType<typeof fetch>;

type RequestOptions = {
  signal?: AbortSignal | null;
  fetch?: FetchFn;
  client?: Client;
};

function getAbortReason(signal: AbortSignal): unknown {
  return signal.reason ?? new DOMException('The operation was aborted.', 'AbortError');
}

function abortError(): DOMException {
  return new DOMException('The operation timed out.', 'TimeoutError');
}

function createTimeoutSignal(timeout: number): AbortSignal | undefined {
  if (!Number.isFinite(timeout) || timeout <= 0) {
    return undefined;
  }

  const abortSignal = AbortSignal as typeof AbortSignal & {
    timeout?: (milliseconds: number) => AbortSignal;
  };

  if (typeof abortSignal.timeout === 'function') {
    return abortSignal.timeout(timeout);
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(abortError()), timeout);
  const unref = (timer as { unref?: () => void }).unref;

  if (typeof unref === 'function') {
    unref.call(timer);
  }

  return controller.signal;
}

function mergeSignals(signals: Array<AbortSignal | undefined>): AbortSignal | undefined {
  const activeSignals = signals.filter((signal): signal is AbortSignal => Boolean(signal));

  if (activeSignals.length === 0) {
    return undefined;
  }

  if (activeSignals.length === 1) {
    return activeSignals[0];
  }

  const alreadyAborted = activeSignals.find((signal) => signal.aborted);

  if (alreadyAborted) {
    const controller = new AbortController();
    controller.abort(getAbortReason(alreadyAborted));
    return controller.signal;
  }

  const abortSignal = AbortSignal as typeof AbortSignal & {
    any?: (signals: AbortSignal[]) => AbortSignal;
  };

  if (typeof abortSignal.any === 'function') {
    return abortSignal.any(activeSignals);
  }

  const controller = new AbortController();
  const onAbort = (event: Event) => {
    const signal = event.target as AbortSignal;
    controller.abort(getAbortReason(signal));

    for (const activeSignal of activeSignals) {
      activeSignal.removeEventListener('abort', onAbort);
    }
  };

  for (const signal of activeSignals) {
    signal.addEventListener('abort', onAbort, { once: true });
  }

  return controller.signal;
}

function raceWithAbort<T>(promise: Promise<T>, signal?: AbortSignal): Promise<T> {
  if (!signal) {
    return promise;
  }

  if (signal.aborted) {
    return Promise.reject(getAbortReason(signal));
  }

  return new Promise<T>((resolve, reject) => {
    const onAbort = () => {
      reject(getAbortReason(signal));
    };

    signal.addEventListener('abort', onAbort, { once: true });
    promise.then(
      (value) => {
        signal.removeEventListener('abort', onAbort);
        resolve(value);
      },
      (error: unknown) => {
        signal.removeEventListener('abort', onAbort);
        reject(error);
      }
    );
  });
}

/**
 * API client for the PostZen Public API.
 */
export class PostZen {
  private readonly _client!: Client;
  private readonly _timeout!: number;

  /**
   * API key used for authentication.
   */
  apiKey!: string;

  /**
   * Base URL for API requests.
   */
  baseURL!: string;

  /**
   * Profiles API - Manage workspace profiles
   */
  profiles = {
    createProfile: ((options?: Parameters<typeof createProfile>[0]) => createProfile(this._withRequestOptions(options) as Parameters<typeof createProfile>[0])) as typeof createProfile,
    deleteProfile: ((options?: Parameters<typeof deleteProfile>[0]) => deleteProfile(this._withRequestOptions(options) as Parameters<typeof deleteProfile>[0])) as typeof deleteProfile,
    getProfile: ((options?: Parameters<typeof getProfile>[0]) => getProfile(this._withRequestOptions(options) as Parameters<typeof getProfile>[0])) as typeof getProfile,
    listProfiles: ((options?: Parameters<typeof listProfiles>[0]) => listProfiles(this._withRequestOptions(options) as Parameters<typeof listProfiles>[0])) as typeof listProfiles,
    updateProfile: ((options?: Parameters<typeof updateProfile>[0]) => updateProfile(this._withRequestOptions(options) as Parameters<typeof updateProfile>[0])) as typeof updateProfile,
  };

  /**
   * Accounts API - Manage connected social accounts
   */
  accounts = {
    createPinterestBoard: ((options?: Parameters<typeof createPinterestBoard>[0]) => createPinterestBoard(this._withRequestOptions(options) as Parameters<typeof createPinterestBoard>[0])) as typeof createPinterestBoard,
    disconnectAccount: ((options?: Parameters<typeof disconnectAccount>[0]) => disconnectAccount(this._withRequestOptions(options) as Parameters<typeof disconnectAccount>[0])) as typeof disconnectAccount,
    getPinterestBoards: ((options?: Parameters<typeof getPinterestBoards>[0]) => getPinterestBoards(this._withRequestOptions(options) as Parameters<typeof getPinterestBoards>[0])) as typeof getPinterestBoards,
    listAccounts: ((options?: Parameters<typeof listAccounts>[0]) => listAccounts(this._withRequestOptions(options) as Parameters<typeof listAccounts>[0])) as typeof listAccounts,
    updatePinterestBoards: ((options?: Parameters<typeof updatePinterestBoards>[0]) => updatePinterestBoards(this._withRequestOptions(options) as Parameters<typeof updatePinterestBoards>[0])) as typeof updatePinterestBoards,
  };

  /**
   * Connect API - OAuth connection flows
   */
  connect = {
    completeConnect: ((options?: Parameters<typeof completeConnect>[0]) => completeConnect(this._withRequestOptions(options) as Parameters<typeof completeConnect>[0])) as typeof completeConnect,
    createConnectUrl: ((options?: Parameters<typeof createConnectUrl>[0]) => createConnectUrl(this._withRequestOptions(options) as Parameters<typeof createConnectUrl>[0])) as typeof createConnectUrl,
    listPinterestBoardsForSelection: ((options?: Parameters<typeof listPinterestBoardsForSelection>[0]) => listPinterestBoardsForSelection(this._withRequestOptions(options) as Parameters<typeof listPinterestBoardsForSelection>[0])) as typeof listPinterestBoardsForSelection,
    selectPinterestBoard: ((options?: Parameters<typeof selectPinterestBoard>[0]) => selectPinterestBoard(this._withRequestOptions(options) as Parameters<typeof selectPinterestBoard>[0])) as typeof selectPinterestBoard,
  };

  /**
   * Media API - Create presigned media uploads
   */
  media = {
    createMediaPresign: ((options?: Parameters<typeof createMediaPresign>[0]) => createMediaPresign(this._withRequestOptions(options) as Parameters<typeof createMediaPresign>[0])) as typeof createMediaPresign,
    uploadMediaDirect: ((options?: Parameters<typeof uploadMediaDirect>[0]) => uploadMediaDirect(this._withRequestOptions(options) as Parameters<typeof uploadMediaDirect>[0])) as typeof uploadMediaDirect,
    /**
     * Upload media in one step: presign, PUT the raw bytes to the returned
     * `uploadUrl`, and resolve with the public URL and metadata.
     */
    upload: (source: MediaUploadSource, options?: MediaUploadOptions): Promise<UploadedMedia> =>
      uploadMedia(source, options, {
        presign: async (body, signal) => {
          const { data } = await this.media.createMediaPresign(signal ? { body, signal } : { body });
          return data!;
        },
        putSignal: (callerSignal) => mergeSignals([callerSignal ?? undefined, createTimeoutSignal(this._timeout)]),
      }),
  };

  /**
   * Posts API - Create, schedule, and publish posts
   */
  posts = {
    bulkUploadPosts: ((options?: Parameters<typeof bulkUploadPosts>[0]) => bulkUploadPosts(this._withRequestOptions(options) as Parameters<typeof bulkUploadPosts>[0])) as typeof bulkUploadPosts,
    createPost: ((options?: Parameters<typeof createPost>[0]) => createPost(this._withRequestOptions(options) as Parameters<typeof createPost>[0])) as typeof createPost,
    deletePost: ((options?: Parameters<typeof deletePost>[0]) => deletePost(this._withRequestOptions(options) as Parameters<typeof deletePost>[0])) as typeof deletePost,
    getPost: ((options?: Parameters<typeof getPost>[0]) => getPost(this._withRequestOptions(options) as Parameters<typeof getPost>[0])) as typeof getPost,
    listPostComments: ((options?: Parameters<typeof listPostComments>[0]) => listPostComments(this._withRequestOptions(options) as Parameters<typeof listPostComments>[0])) as typeof listPostComments,
    listPostReactions: ((options?: Parameters<typeof listPostReactions>[0]) => listPostReactions(this._withRequestOptions(options) as Parameters<typeof listPostReactions>[0])) as typeof listPostReactions,
    listPosts: ((options?: Parameters<typeof listPosts>[0]) => listPosts(this._withRequestOptions(options) as Parameters<typeof listPosts>[0])) as typeof listPosts,
    updatePost: ((options?: Parameters<typeof updatePost>[0]) => updatePost(this._withRequestOptions(options) as Parameters<typeof updatePost>[0])) as typeof updatePost,
  };

  /**
   * apikeys API
   */
  apikeys = {
    createApiKey: ((options?: Parameters<typeof createApiKey>[0]) => createApiKey(this._withRequestOptions(options) as Parameters<typeof createApiKey>[0])) as typeof createApiKey,
    deleteApiKey: ((options?: Parameters<typeof deleteApiKey>[0]) => deleteApiKey(this._withRequestOptions(options) as Parameters<typeof deleteApiKey>[0])) as typeof deleteApiKey,
    listApiKeys: ((options?: Parameters<typeof listApiKeys>[0]) => listApiKeys(this._withRequestOptions(options) as Parameters<typeof listApiKeys>[0])) as typeof listApiKeys,
  };

  /**
   * commentautomations API
   */
  commentautomations = {
    createCommentAutomation: ((options?: Parameters<typeof createCommentAutomation>[0]) => createCommentAutomation(this._withRequestOptions(options) as Parameters<typeof createCommentAutomation>[0])) as typeof createCommentAutomation,
    deleteCommentAutomation: ((options?: Parameters<typeof deleteCommentAutomation>[0]) => deleteCommentAutomation(this._withRequestOptions(options) as Parameters<typeof deleteCommentAutomation>[0])) as typeof deleteCommentAutomation,
    getCommentAutomation: ((options?: Parameters<typeof getCommentAutomation>[0]) => getCommentAutomation(this._withRequestOptions(options) as Parameters<typeof getCommentAutomation>[0])) as typeof getCommentAutomation,
    listCommentAutomationLogs: ((options?: Parameters<typeof listCommentAutomationLogs>[0]) => listCommentAutomationLogs(this._withRequestOptions(options) as Parameters<typeof listCommentAutomationLogs>[0])) as typeof listCommentAutomationLogs,
    listCommentAutomations: ((options?: Parameters<typeof listCommentAutomations>[0]) => listCommentAutomations(this._withRequestOptions(options) as Parameters<typeof listCommentAutomations>[0])) as typeof listCommentAutomations,
    updateCommentAutomation: ((options?: Parameters<typeof updateCommentAutomation>[0]) => updateCommentAutomation(this._withRequestOptions(options) as Parameters<typeof updateCommentAutomation>[0])) as typeof updateCommentAutomation,
  };

  /**
   * queues API
   */
  queues = {
    createQueueSlot: ((options?: Parameters<typeof createQueueSlot>[0]) => createQueueSlot(this._withRequestOptions(options) as Parameters<typeof createQueueSlot>[0])) as typeof createQueueSlot,
    deleteQueueSlot: ((options?: Parameters<typeof deleteQueueSlot>[0]) => deleteQueueSlot(this._withRequestOptions(options) as Parameters<typeof deleteQueueSlot>[0])) as typeof deleteQueueSlot,
    getNextQueueSlot: ((options?: Parameters<typeof getNextQueueSlot>[0]) => getNextQueueSlot(this._withRequestOptions(options) as Parameters<typeof getNextQueueSlot>[0])) as typeof getNextQueueSlot,
    listQueueSlots: ((options?: Parameters<typeof listQueueSlots>[0]) => listQueueSlots(this._withRequestOptions(options) as Parameters<typeof listQueueSlots>[0])) as typeof listQueueSlots,
    previewQueue: ((options?: Parameters<typeof previewQueue>[0]) => previewQueue(this._withRequestOptions(options) as Parameters<typeof previewQueue>[0])) as typeof previewQueue,
    updateQueueSlot: ((options?: Parameters<typeof updateQueueSlot>[0]) => updateQueueSlot(this._withRequestOptions(options) as Parameters<typeof updateQueueSlot>[0])) as typeof updateQueueSlot,
  };

  /**
   * webhooks API
   */
  webhooks = {
    createWebhook: ((options?: Parameters<typeof createWebhook>[0]) => createWebhook(this._withRequestOptions(options) as Parameters<typeof createWebhook>[0])) as typeof createWebhook,
    deleteWebhook: ((options?: Parameters<typeof deleteWebhook>[0]) => deleteWebhook(this._withRequestOptions(options) as Parameters<typeof deleteWebhook>[0])) as typeof deleteWebhook,
    getWebhook: ((options?: Parameters<typeof getWebhook>[0]) => getWebhook(this._withRequestOptions(options) as Parameters<typeof getWebhook>[0])) as typeof getWebhook,
    listWebhookDeliveries: ((options?: Parameters<typeof listWebhookDeliveries>[0]) => listWebhookDeliveries(this._withRequestOptions(options) as Parameters<typeof listWebhookDeliveries>[0])) as typeof listWebhookDeliveries,
    listWebhooks: ((options?: Parameters<typeof listWebhooks>[0]) => listWebhooks(this._withRequestOptions(options) as Parameters<typeof listWebhooks>[0])) as typeof listWebhooks,
    redeliverWebhookDelivery: ((options?: Parameters<typeof redeliverWebhookDelivery>[0]) => redeliverWebhookDelivery(this._withRequestOptions(options) as Parameters<typeof redeliverWebhookDelivery>[0])) as typeof redeliverWebhookDelivery,
    testWebhook: ((options?: Parameters<typeof testWebhook>[0]) => testWebhook(this._withRequestOptions(options) as Parameters<typeof testWebhook>[0])) as typeof testWebhook,
    updateWebhook: ((options?: Parameters<typeof updateWebhook>[0]) => updateWebhook(this._withRequestOptions(options) as Parameters<typeof updateWebhook>[0])) as typeof updateWebhook,
  };

  /**
   * inbox API
   */
  inbox = {
    deleteInboxComment: ((options?: Parameters<typeof deleteInboxComment>[0]) => deleteInboxComment(this._withRequestOptions(options) as Parameters<typeof deleteInboxComment>[0])) as typeof deleteInboxComment,
    getInboxConversation: ((options?: Parameters<typeof getInboxConversation>[0]) => getInboxConversation(this._withRequestOptions(options) as Parameters<typeof getInboxConversation>[0])) as typeof getInboxConversation,
    hideInboxComment: ((options?: Parameters<typeof hideInboxComment>[0]) => hideInboxComment(this._withRequestOptions(options) as Parameters<typeof hideInboxComment>[0])) as typeof hideInboxComment,
    listInboxConversationMessages: ((options?: Parameters<typeof listInboxConversationMessages>[0]) => listInboxConversationMessages(this._withRequestOptions(options) as Parameters<typeof listInboxConversationMessages>[0])) as typeof listInboxConversationMessages,
    listInboxConversations: ((options?: Parameters<typeof listInboxConversations>[0]) => listInboxConversations(this._withRequestOptions(options) as Parameters<typeof listInboxConversations>[0])) as typeof listInboxConversations,
    listInboxPostComments: ((options?: Parameters<typeof listInboxPostComments>[0]) => listInboxPostComments(this._withRequestOptions(options) as Parameters<typeof listInboxPostComments>[0])) as typeof listInboxPostComments,
    markInboxConversationRead: ((options?: Parameters<typeof markInboxConversationRead>[0]) => markInboxConversationRead(this._withRequestOptions(options) as Parameters<typeof markInboxConversationRead>[0])) as typeof markInboxConversationRead,
    replyToInboxPost: ((options?: Parameters<typeof replyToInboxPost>[0]) => replyToInboxPost(this._withRequestOptions(options) as Parameters<typeof replyToInboxPost>[0])) as typeof replyToInboxPost,
    searchInboxConversations: ((options?: Parameters<typeof searchInboxConversations>[0]) => searchInboxConversations(this._withRequestOptions(options) as Parameters<typeof searchInboxConversations>[0])) as typeof searchInboxConversations,
    sendInboxMessage: ((options?: Parameters<typeof sendInboxMessage>[0]) => sendInboxMessage(this._withRequestOptions(options) as Parameters<typeof sendInboxMessage>[0])) as typeof sendInboxMessage,
    unhideInboxComment: ((options?: Parameters<typeof unhideInboxComment>[0]) => unhideInboxComment(this._withRequestOptions(options) as Parameters<typeof unhideInboxComment>[0])) as typeof unhideInboxComment,
    updateInboxConversation: ((options?: Parameters<typeof updateInboxConversation>[0]) => updateInboxConversation(this._withRequestOptions(options) as Parameters<typeof updateInboxConversation>[0])) as typeof updateInboxConversation,
  };

  /**
   * analytics API
   */
  analytics = {
    getAnalytics: ((options?: Parameters<typeof getAnalytics>[0]) => getAnalytics(this._withRequestOptions(options) as Parameters<typeof getAnalytics>[0])) as typeof getAnalytics,
    getBestTimeToPost: ((options?: Parameters<typeof getBestTimeToPost>[0]) => getBestTimeToPost(this._withRequestOptions(options) as Parameters<typeof getBestTimeToPost>[0])) as typeof getBestTimeToPost,
    getDailyMetrics: ((options?: Parameters<typeof getDailyMetrics>[0]) => getDailyMetrics(this._withRequestOptions(options) as Parameters<typeof getDailyMetrics>[0])) as typeof getDailyMetrics,
    getFollowerStats: ((options?: Parameters<typeof getFollowerStats>[0]) => getFollowerStats(this._withRequestOptions(options) as Parameters<typeof getFollowerStats>[0])) as typeof getFollowerStats,
    getPostTimeline: ((options?: Parameters<typeof getPostTimeline>[0]) => getPostTimeline(this._withRequestOptions(options) as Parameters<typeof getPostTimeline>[0])) as typeof getPostTimeline,
    syncExternalPosts: ((options?: Parameters<typeof syncExternalPosts>[0]) => syncExternalPosts(this._withRequestOptions(options) as Parameters<typeof syncExternalPosts>[0])) as typeof syncExternalPosts,
  };

  constructor(options: ClientOptions = {}) {
    const apiKey = options.apiKey ?? process.env.POSTZEN_API_KEY;

    if (!apiKey) {
      throw new PostZenApiError(
        "The POSTZEN_API_KEY environment variable is missing or empty. Provide it in the environment or instantiate the client with new PostZen({ apiKey: 'pzn_live_...' }).",
        401,
        'missing_api_key'
      );
    }

    this.apiKey = apiKey;
    this.baseURL = options.baseURL ?? 'https://api.postzen.dev';
    this._timeout = options.timeout ?? 60000;
    this._client = createClient(
      createConfig({
        baseUrl: this.baseURL,
        headers: {
          'User-Agent': `postzen-node/${packageJson.version}`,
          ...(options.defaultHeaders ?? {}),
        },
      })
    );

    this._client.interceptors.request.use((request: Request) => {
      request.headers.set('Authorization', `Bearer ${this.apiKey}`);
      return request;
    });

    this._client.interceptors.response.use(async (response: Response) => {
      if (response.ok) {
        return response;
      }

      let body: Record<string, unknown> | undefined;

      try {
        body = (await response.clone().json()) as Record<string, unknown>;
      } catch {
        body = undefined;
      }

      throw parseApiError(response, body);
    });
  }

  private _withRequestOptions(options?: RequestOptions): RequestOptions & { client: Client } {
    const requestOptions = {
      ...(options ?? {}),
    } as RequestOptions & { client: Client };
    const timeoutSignal = createTimeoutSignal(this._timeout);
    const callerSignal = options?.signal ?? undefined;

    requestOptions.client = this._client;
    requestOptions.signal = mergeSignals([callerSignal, timeoutSignal]);

    if (options?.fetch) {
      requestOptions.fetch = this._wrapFetch(options.fetch);
    }

    return requestOptions;
  }

  private _wrapFetch(fetchImpl: FetchFn): FetchFn {
    return (request: Request) => {
      return raceWithAbort(fetchImpl(request), request.signal ?? undefined);
    };
  }
}

export default PostZen;
